-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE inspections (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  property_type TEXT NOT NULL DEFAULT 'apartment',
  status TEXT NOT NULL DEFAULT 'draft',
  general_notes TEXT DEFAULT '',
  property_data TEXT DEFAULT '{}',
  tenant_data TEXT DEFAULT '{}',
  landlord_data TEXT DEFAULT '{}',
  agent_data TEXT DEFAULT '{}',
  tenancy_data TEXT DEFAULT '{}',
  rooms_data TEXT DEFAULT '[]',
  property_items TEXT DEFAULT '[]',
  signatures TEXT DEFAULT '[]',
  overall_photos TEXT DEFAULT '[]',
  payment_data TEXT DEFAULT '{}',
  report_generated INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at TEXT
, pdf_url TEXT DEFAULT '');

CREATE TABLE items (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT DEFAULT '',
  condition TEXT,
  comments TEXT DEFAULT '',
  checked INTEGER DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  environment TEXT NOT NULL DEFAULT 'staging',
  user_id TEXT NOT NULL,
  inspection_id TEXT,
  price_id INTEGER REFERENCES payment_prices(id),
  amount INTEGER NOT NULL,
  currency TEXT DEFAULT 'AED',
  status TEXT DEFAULT 'pending',
  type TEXT DEFAULT 'one_time',
  provider TEXT DEFAULT 'stripe',
  provider_session_id TEXT,
  provider_payment_id TEXT,
  discount_code TEXT,
  discount_amount INTEGER DEFAULT 0,
  metadata TEXT,
  paid_at INTEGER,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE parties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  inspection_id TEXT NOT NULL,
  role TEXT NOT NULL,
  name TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  company_name TEXT DEFAULT '',
  trade_license TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE payment_prices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  environment TEXT NOT NULL DEFAULT 'staging',
  name TEXT NOT NULL,
  description TEXT,
  amount INTEGER NOT NULL,
  currency TEXT DEFAULT 'AED',
  type TEXT DEFAULT 'one_time',
  interval TEXT,
  provider TEXT NOT NULL DEFAULT 'stripe',
  provider_product_id TEXT,
  provider_price_id TEXT,
  active INTEGER DEFAULT 1,
  metadata TEXT,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  inspection_id TEXT NOT NULL,
  paid INTEGER DEFAULT 0,
  amount INTEGER DEFAULT 0,
  currency TEXT DEFAULT 'AED',
  method TEXT DEFAULT 'card',
  paid_at TEXT,
  transaction_id TEXT,
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE photos (
  id TEXT PRIMARY KEY,
  item_id TEXT,
  inspection_id TEXT NOT NULL,
  photo_type TEXT NOT NULL DEFAULT 'item',
  url TEXT NOT NULL,
  caption TEXT DEFAULT '',
  timestamp TEXT NOT NULL,
  gps_lat REAL,
  gps_lng REAL,
  sort_order INTEGER DEFAULT 0,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE property_details (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  inspection_id TEXT NOT NULL UNIQUE,
  makani_number TEXT DEFAULT '',
  area TEXT DEFAULT '',
  city TEXT DEFAULT 'Dubai',
  building_name TEXT DEFAULT '',
  unit_number TEXT DEFAULT '',
  total_area_sqft INTEGER,
  bedrooms INTEGER DEFAULT 1,
  bathrooms INTEGER DEFAULT 1,
  furnished INTEGER DEFAULT 0,
  special_features TEXT DEFAULT '[]',
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE rooms (
  id TEXT PRIMARY KEY,
  inspection_id TEXT NOT NULL,
  name TEXT NOT NULL,
  room_type TEXT NOT NULL,
  icon TEXT DEFAULT '🏠',
  overall_comments TEXT DEFAULT '',
  overall_condition TEXT,
  sort_order INTEGER DEFAULT 0,
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE signatures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  inspection_id TEXT NOT NULL,
  role TEXT NOT NULL,
  name TEXT NOT NULL,
  data_url TEXT NOT NULL,
  signed_at TEXT NOT NULL,
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE tenancy_details (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  inspection_id TEXT NOT NULL UNIQUE,
  lease_start TEXT DEFAULT '',
  lease_end TEXT DEFAULT '',
  contract_number TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE user_profiles (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL UNIQUE,
  phone TEXT DEFAULT '',
  location TEXT DEFAULT '',
  inspector_name TEXT DEFAULT '',
  inspector_email TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  phone TEXT DEFAULT '',
  location TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, password_hash TEXT DEFAULT '', is_tester INTEGER DEFAULT 0, free_inspections INTEGER DEFAULT 0);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_inspections_created_at ON inspections(created_at DESC);

CREATE INDEX idx_inspections_status ON inspections(status);

CREATE INDEX idx_inspections_user_id ON inspections(user_id);

CREATE INDEX idx_orders_env_status ON orders(environment, status);

CREATE INDEX idx_orders_env_user ON orders(environment, user_id);

CREATE INDEX idx_parties_inspection ON parties(inspection_id);

CREATE INDEX idx_prices_env ON payment_prices(environment, provider, provider_price_id);

CREATE INDEX idx_tenancy_inspection ON tenancy_details(inspection_id);

CREATE INDEX idx_user_profiles_user_id ON user_profiles(user_id);

CREATE INDEX idx_users_email ON users(email);
