// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { inspections, parties, tenancyDetails, paymentPrices, orders, propertyDetails, rooms, items, photos, signatures, payments } from "./db_schema";

export const partiesRelations = relations(parties, ({one}) => ({
	inspection: one(inspections, {
		fields: [parties.inspectionId],
		references: [inspections.id]
	}),
}));

export const inspectionsRelations = relations(inspections, ({many}) => ({
	parties: many(parties),
	tenancyDetails: many(tenancyDetails),
	propertyDetails: many(propertyDetails),
	photos: many(photos),
	signatures: many(signatures),
	rooms: many(rooms),
	payments: many(payments),
}));

export const tenancyDetailsRelations = relations(tenancyDetails, ({one}) => ({
	inspection: one(inspections, {
		fields: [tenancyDetails.inspectionId],
		references: [inspections.id]
	}),
}));

export const ordersRelations = relations(orders, ({one}) => ({
	paymentPrice: one(paymentPrices, {
		fields: [orders.priceId],
		references: [paymentPrices.id]
	}),
}));

export const paymentPricesRelations = relations(paymentPrices, ({many}) => ({
	orders: many(orders),
}));

export const propertyDetailsRelations = relations(propertyDetails, ({one}) => ({
	inspection: one(inspections, {
		fields: [propertyDetails.inspectionId],
		references: [inspections.id]
	}),
}));

export const itemsRelations = relations(items, ({one, many}) => ({
	room: one(rooms, {
		fields: [items.roomId],
		references: [rooms.id]
	}),
	photos: many(photos),
}));

export const roomsRelations = relations(rooms, ({one, many}) => ({
	items: many(items),
	inspection: one(inspections, {
		fields: [rooms.inspectionId],
		references: [inspections.id]
	}),
}));

export const photosRelations = relations(photos, ({one}) => ({
	inspection: one(inspections, {
		fields: [photos.inspectionId],
		references: [inspections.id]
	}),
	item: one(items, {
		fields: [photos.itemId],
		references: [items.id]
	}),
}));

export const signaturesRelations = relations(signatures, ({one}) => ({
	inspection: one(inspections, {
		fields: [signatures.inspectionId],
		references: [inspections.id]
	}),
}));

export const paymentsRelations = relations(payments, ({one}) => ({
	inspection: one(inspections, {
		fields: [payments.inspectionId],
		references: [inspections.id]
	}),
}));