// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey, real } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const inspections = sqliteTable("inspections", {
	id: text().primaryKey(),
	userId: text("user_id").notNull(),
	propertyType: text("property_type").default("apartment").notNull(),
	status: text().default("draft").notNull(),
	generalNotes: text("general_notes").default(""),
	propertyData: text("property_data").default("{}"),
	tenantData: text("tenant_data").default("{}"),
	landlordData: text("landlord_data").default("{}"),
	agentData: text("agent_data").default("{}"),
	tenancyData: text("tenancy_data").default("{}"),
	roomsData: text("rooms_data").default("[]"),
	propertyItems: text("property_items").default("[]"),
	signatures: text().default("[]"),
	overallPhotos: text("overall_photos").default("[]"),
	paymentData: text("payment_data").default("{}"),
	reportGenerated: integer("report_generated").default(0),
	createdAt: text("created_at").default("sql`(datetime('now'))`").notNull(),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`").notNull(),
	completedAt: text("completed_at"),
	pdfUrl: text("pdf_url").default(""),
},
(table) => [
	index("idx_inspections_created_at").on(table.createdAt),
	index("idx_inspections_status").on(table.status),
	index("idx_inspections_user_id").on(table.userId),
]);

export const users = sqliteTable("users", {
	id: text().primaryKey(),
	email: text().notNull(),
	name: text().notNull(),
	phone: text().default(""),
	location: text().default(""),
	createdAt: text("created_at").default("sql`(datetime('now'))`").notNull(),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`").notNull(),
	passwordHash: text("password_hash").default(""),
	isTester: integer("is_tester").default(0),
	freeInspections: integer("free_inspections").default(0),
},
(table) => [
	index("idx_users_email").on(table.email),
]);

export const parties = sqliteTable("parties", {
	id: integer().primaryKey({ autoIncrement: true }),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	role: text().notNull(),
	name: text().default(""),
	phone: text().default(""),
	email: text().default(""),
	companyName: text("company_name").default(""),
	tradeLicense: text("trade_license").default(""),
	createdAt: text("created_at").default("sql`(datetime('now'))`").notNull(),
},
(table) => [
	index("idx_parties_inspection").on(table.inspectionId),
]);

export const tenancyDetails = sqliteTable("tenancy_details", {
	id: integer().primaryKey({ autoIncrement: true }),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	leaseStart: text("lease_start").default(""),
	leaseEnd: text("lease_end").default(""),
	contractNumber: text("contract_number").default(""),
	createdAt: text("created_at").default("sql`(datetime('now'))`").notNull(),
},
(table) => [
	index("idx_tenancy_inspection").on(table.inspectionId),
]);

export const paymentPrices = sqliteTable("payment_prices", {
	id: integer().primaryKey({ autoIncrement: true }),
	environment: text().default("staging").notNull(),
	name: text().notNull(),
	description: text(),
	amount: integer().notNull(),
	currency: text().default("AED"),
	type: text().default("one_time"),
	interval: text(),
	provider: text().default("stripe").notNull(),
	providerProductId: text("provider_product_id"),
	providerPriceId: text("provider_price_id"),
	active: integer().default(1),
	metadata: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_prices_env").on(table.environment, table.provider, table.providerPriceId),
]);

export const orders = sqliteTable("orders", {
	id: integer().primaryKey({ autoIncrement: true }),
	environment: text().default("staging").notNull(),
	userId: text("user_id").notNull(),
	inspectionId: text("inspection_id"),
	priceId: integer("price_id").references(() => paymentPrices.id),
	amount: integer().notNull(),
	currency: text().default("AED"),
	status: text().default("pending"),
	type: text().default("one_time"),
	provider: text().default("stripe"),
	providerSessionId: text("provider_session_id"),
	providerPaymentId: text("provider_payment_id"),
	discountCode: text("discount_code"),
	discountAmount: integer("discount_amount").default(0),
	metadata: text(),
	paidAt: integer("paid_at"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_orders_env_status").on(table.environment, table.status),
	index("idx_orders_env_user").on(table.environment, table.userId),
]);

export const propertyDetails = sqliteTable("property_details", {
	id: integer().primaryKey({ autoIncrement: true }),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	makaniNumber: text("makani_number").default(""),
	area: text().default(""),
	city: text().default("Dubai"),
	buildingName: text("building_name").default(""),
	unitNumber: text("unit_number").default(""),
	totalAreaSqft: integer("total_area_sqft"),
	bedrooms: integer().default(1),
	bathrooms: integer().default(1),
	furnished: integer().default(0),
	specialFeatures: text("special_features").default("[]"),
});

export const items = sqliteTable("items", {
	id: text().primaryKey(),
	roomId: text("room_id").notNull().references(() => rooms.id, { onDelete: "cascade" } ),
	name: text().notNull(),
	category: text().default(""),
	condition: text(),
	comments: text().default(""),
	checked: integer().default(0),
	sortOrder: integer("sort_order").default(0),
});

export const photos = sqliteTable("photos", {
	id: text().primaryKey(),
	itemId: text("item_id").references(() => items.id, { onDelete: "cascade" } ),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	photoType: text("photo_type").default("item").notNull(),
	url: text().notNull(),
	caption: text().default(""),
	timestamp: text().notNull(),
	gpsLat: real("gps_lat"),
	gpsLng: real("gps_lng"),
	sortOrder: integer("sort_order").default(0),
});

export const signatures = sqliteTable("signatures", {
	id: integer().primaryKey({ autoIncrement: true }),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	role: text().notNull(),
	name: text().notNull(),
	dataUrl: text("data_url").notNull(),
	signedAt: text("signed_at").notNull(),
});

export const rooms = sqliteTable("rooms", {
	id: text().primaryKey(),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	name: text().notNull(),
	roomType: text("room_type").notNull(),
	icon: text().default("🏠"),
	overallComments: text("overall_comments").default(""),
	overallCondition: text("overall_condition"),
	sortOrder: integer("sort_order").default(0),
});

export const payments = sqliteTable("payments", {
	id: integer().primaryKey({ autoIncrement: true }),
	inspectionId: text("inspection_id").notNull().references(() => inspections.id, { onDelete: "cascade" } ),
	paid: integer().default(0),
	amount: integer().default(0),
	currency: text().default("AED"),
	method: text().default("card"),
	paidAt: text("paid_at"),
	transactionId: text("transaction_id"),
});

export const userProfiles = sqliteTable("user_profiles", {
	id: text().primaryKey(),
	userId: text("user_id").notNull(),
	phone: text().default(""),
	location: text().default(""),
	inspectorName: text("inspector_name").default(""),
	inspectorEmail: text("inspector_email").default(""),
	createdAt: text("created_at").default("sql`(datetime('now'))`").notNull(),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`").notNull(),
},
(table) => [
	index("idx_user_profiles_user_id").on(table.userId),
]);

